_BASE_: "../Base-BoxSnake-RCNN-FPN.yaml"
MODEL:
  RPN:
    LOSS_WEIGHT: 1.0
    BBOX_REG_LOSS_WEIGHT: 1.0
  #WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_CLS_LOSS_WEIGHT: 1.0
  MASK_ON: True
  ROI_MASK_HEAD:
    NAME: "Shape2pointHead"
    POOLER_TYPE: ""
  POLYGON_HEAD:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    PRED_WITHIN_BOX: False
    #POLY_NUM_PTS: 64
    POLY_NUM_PTS: 8 # lmc
    CLS_AGNOSTIC_MASK: True
    PREPOOL: False
    UPSAMPLING: False
    # lmc
    shape_point_num: 8 # lmc
    shape_para: [1, 1, 0.5, 0.5, 0.5] # lmc
    whratio: 0.2  # lmc
    KAN: False  # lmc
    MLP_KAN: False  # lmc
    USE_CLS_TOKEN: True
    SHAPE_NUM_DEC_LAYERS: 2 # lmc
    POINT_NUM_DEC_LAYERS: 2 # lmc
    MERGE: False
    MERGE_WEIGHT: 0.5
    DECODE_GAT: False
    FUSION_GAT: False
    MODEL_DIM: 128 # channel
    CROSS_POINTS: 8
  DIFFRAS:  #
    RESOLUTIONS: (64, 64, 64, 64, 64, 64, 64, 64)
    USE_RASTERIZED_GT: False
    INV_SMOOTHNESS_SCHED: (0.1,)
  RESNETS:
    DEPTH: 34 # lmc
    RES2_OUT_CHANNELS: 64 # lmc channel
  ROI_HEADS:
    #SIZE_INPUT: True # lmclmc
    PROPOSAL_ONLY_GT: False
    'NUM_CLASSES': 3 # lmc metal
    'SIZE_INPUT': False
  FCOS:
    'NUM_CLASSES': 3 # lmc metal
  BOX_SUP:
    ENABLE: True
    LOSS_POINTS_SHAPE: False # lmc
    LOSS_POINTS_SHAPE_WEIGHT: 1.0 # lmc 1.0
    LOSS_POINTS_RELA: False
    LOSS_POINTS_RELA_WEIGHT: 1.0 # lmc 1.0
    LOSS_POINTSSHAPE_SUP: False
    LOSS_POINTSSHAPE_SUP_WEIGHT: 0.005 # lmc 1.0
    LOSS_POINTS_PROJ: True
    LOSS_POINTS_PROJ_WEIGHT: 1.0 # 1.0
    LOSS_LOCAL_PAIRWISE: True
    #LOSS_PAIRWISE_WARMUP_ITER: 10000
    LOSS_PAIRWISE_WARMUP_ITER: 1000
    LOCAL_PAIRWISE_KERNEL_SIZE: 3
    LOCAL_PAIRWISE_DILATION: 2
    LOSS_LOCAL_PAIRWISE_WEIGHT: 0.5 #0.5
    LOSS_GLOBAL_PAIRWISE: True
    LOSS_GLOBAL_PAIRWISE_WEIGHT: 0.03 #0.03
    CROP_PREDICTS: True
    CROP_SIZE: 64
    MASK_PADDING_SIZE: 4
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 1e-4
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 8
  CLIP_GRADIENTS:
    ENABLED: False
  LR_SCHEDULER_NAME : "WarmupMultiStepLR"
  STEPS: []
  GAMMA: 1.0
  WARMUP_ITERS: 0
DATASETS:
  TRAIN: ("metal_train",)
  TEST: ("metal_test",)
VIS_PERIOD: 0
TEST:
  EVAL_PERIOD: 1000
  #EVAL_PERIOD: 10

INPUT:
  RB_L : 0.7
  RB_H : 1.3
  RC_L : 0.7
  RC_H : 1.3
  RS_L : 0.7
  RS_H : 1.3
  CROP:
    ENABLED: True
    TYPE: "relative"  # "absolute"
    SIZE: [0.8, 0.8]