MODEL:
  META_ARCHITECTURE: "NewGeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 128
  ANCHOR_GENERATOR:
    SIZES: [[16, 32], [32, 64], [64, 128], [128, 256], [256, 512]]
    ASPECT_RATIOS: [[0.25, 0.5, 1.0, 2.0, 4.0]]
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeadsV2"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  POLYGON_HEAD:
    MERGE_WEIGHT: 0.5
DATASETS:
  TRAIN: ("coco_metal_train",)
  TEST: ("coco_metal_test",)

INPUT:
  MIN_SIZE_TRAIN: (512, 512)
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  FORMAT: BGR
  RANDOM_FLIP: none
VERSION: 2
DATALOADER:
  NUM_WORKERS: 0

